name: Update Subscription

on:
  schedule:
    - cron: '0 */6 * * *'  # هر ۶ ساعت
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Download and check file
        run: |
          curl -s https://raw.githubusercontent.com/davudsedft/purvpn/refs/heads/main/links/purkow.txt -o temp.txt
          
          echo "📦 Downloaded content:"
          cat temp.txt || echo "(Nothing downloaded)"

          if [ ! -s temp.txt ]; then
            echo "❌ Downloaded file is empty. Skipping update."
            exit 1
          fi

          mv temp.txt Config/all.txt

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "✅ No changes to commit."
          else
            git add Config/all.txt
            git commit -m "🔄 Auto-update all.txt"
            git push
          fi
